name: designerdev
favicon: null
layout_spectrum: 0.95673
typography_spectrum: 0.87056
title: Devin Rajaram
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5c4f49'
    - '#18181a'
    - '#ba7e4d'
    - '#462a27'
    - '#cd9765'
  brandStrength: 0.875
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
